name: Windows
on: [push, pull_request, workflow_dispatch]

env:
  php_version: 8.3.2-Win32-vs16-x64
  cef_version: 121.2.14+ga44b59f+chromium-121.0.6167.75_windows64_beta
jobs:
  build:
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
          version: ["8.3"]
          arch: [x64]
    if: ${{ success() || failure() }}
    runs-on: windows-latest
    name: Windows, PHP v${{matrix.version}}, chrome embedded
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Fetch PHP
        run: |
          dir
          curl -LO https://windows.php.net/downloads/releases/php-${{ env.php_version }}.zip 
          dir
          7z x php-${{ env.php_version }}.zip -osrc/php/
          dir src\php\
          
      - name: Fetch Chromium Embedded Framework (CEF)
        uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9
        with:
          url: "https://cef-builds.spotifycdn.com/cef_binary_${{ env.cef_version }}.tar.bz2"
          target: ./
          filename: cef.tar.bz2
          
      - name: Unpack Chromium Embedded Framework (CEF)
        run: |
          dir
          dir src\cef\
          7z x cef.tar.bz2 -o./
          dir
          7z x cef.tar -o./
          dir
          echo Copy Files to target Folder ("cef_binary_${{ env.cef_version }}/*" to src\cef\)
          xcopy /E /H /Y "cef_binary_${{ env.cef_version }}\*" .\src\cef\
          dir src\cef\

      - name: Copy overrides to CEF
        run: |
          xcopy /E /H /Y .\src\cef\overrides\* .\src\cef\
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.2
            
      - name: Build CEF wrapper
        run: |
          cmake -S .\src\cef -B .\src\cef\build
          msbuild .\src\cef\build\libcef_dll_wrapper\libcef_dll_wrapper.vcxproj -t:rebuild -property:Configuration=Release
          
      - name: Copy CEF lib to target directory
        run: |
          dir .\src\
          copy .\src\cef\Release\libcef.dll .\src\
          copy .\src\cef\Release\libcef.lib .\src\
          dir .\src\
          
      - name: Copy CEF wrapper to target directory
        run: |
          dir .\src\
          copy .\src\cef\build\libcef_dll_wrapper\Release\libcef_dll_wrapper.lib .\src\
          dir .\src\
            
      - name: Build app for release
        continue-on-error: true
        run: |
          msbuild src\phpdesktop-chrome.vcxproj -t:rebuild -property:Configuration=Release
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-chromium-embedded-${{matrix.version}}
          path: ./src
